"""add wifi point version

Revision ID: 025a4f081e39
Revises: bc70566fbc19
Create Date: 2026-03-27 14:37:36.491918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025a4f081e39'
down_revision: Union[str, Sequence[str], None] = 'bc70566fbc19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wifi_points_version',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wifi_points_location', 'wifi_points', ['location'], unique=False, postgresql_using='gist')
    op.create_unique_constraint(None, 'wifi_points', ['original_id'])
    op.drop_column('wifi_points', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wifi_points', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'wifi_points', type_='unique')
    op.drop_index('ix_wifi_points_location', table_name='wifi_points', postgresql_using='gist')
    op.drop_table('wifi_points_version')
    # ### end Alembic commands ###
